# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
      config.vm.box = "ubuntu/trusty64"  
	  config.vm.network "private_network", ip: "192.168.33.46"
	  config.vm.provider "virtualbox" do |vb|
	     vb.memory = 2048
	     vb.name = "master1c"
      end
      config.vm.provision :shell, :path => "scripts/bootmaster1.sh"
 
end
