# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
      config.vm.box = "ubuntu/trusty64"  
	  config.vm.network "private_network", ip: "192.168.33.41"
	  config.vm.provider "virtualbox" do |vb|
	     vb.memory = 2048
	     vb.name = "master1"
      end

      config.vm.provision "shell" do |s|
          s.path = "scripts/bootmaster1.sh"
          s.args   = ["192.168.33.41", "192.168.33.42", "192.168.33.41", "1", "2", "1"]
      end
end