# -*- mode: ruby -*-
# vi: set ft=ruby :

# Explanation of script arguments for Mesos masters:
# IP_THIS_VM=$1
# HOSTNAME_THIS_VM=$2
# ID_THIS_VM=$3
# IP_1ST_MSTR=$4
# IP_2ND_MSTR=$5
# IP_3RD_MSTR=$6
# ID_1ST_MSTR=$7
# ID_2ND_MSTR=$8
# ID_3RD_MSTR=$9

Vagrant.configure(2) do |config|

   config.vm.define :mesos1 do |mesos1|
      mesos1.vm.box = "ubuntu/trusty64"  
	  mesos1.vm.network "private_network", ip: "192.168.33.61"
	  mesos1.vm.provider "virtualbox" do |vb|
	     vb.memory = 2048
	     vb.name = "mesos1"
      end	  
      mesos1.vm.provision "shell" do |s|
          s.path = "scripts/bootmesos.sh"
          s.args   = ["192.168.33.61", "192.168.33.61", "1", 
		              "192.168.33.61", "192.168.33.62", "192.168.33.63",
					  "1", "2", "3"]
      end
   end
	  
   config.vm.define :mesos2 do |mesos2|
      mesos2.vm.box = "ubuntu/trusty64"  
	  mesos2.vm.network "private_network", ip: "192.168.33.62"
	  mesos2.vm.provider "virtualbox" do |vb|
	     vb.memory = 2048
	     vb.name = "mesos2"
      end
      mesos2.vm.provision "shell" do |s|
          s.path = "scripts/bootmesos.sh"
          s.args   = ["192.168.33.62", "192.168.33.62", "2", 
		              "192.168.33.61", "192.168.33.62", "192.168.33.63",
					  "1", "2", "3"]
      end
   end
   
   config.vm.define :mesos3 do |mesos3|
      mesos3.vm.box = "ubuntu/trusty64"  
	  mesos3.vm.network "private_network", ip: "192.168.33.63"
	  mesos3.vm.provider "virtualbox" do |vb|
	     vb.memory = 2048
	     vb.name = "mesos3"
      end
      mesos3.vm.provision "shell" do |s|
          s.path = "scripts/bootmesos.sh"
          s.args   = ["192.168.33.63", "192.168.33.63", "3", 
		              "192.168.33.61", "192.168.33.62", "192.168.33.63",
					  "1", "2", "3"]
      end
   end
   
   config.vm.define :slave1 do |slave1|
      slave1.vm.box = "ubuntu/trusty64"  
	  slave1.vm.network "private_network", ip: "192.168.33.71"
	  slave1.vm.provider "virtualbox" do |vb|
	     vb.memory = 2048
	     vb.name = "slave1"
      end
      slave1.vm.provision "shell" do |s|
          s.path = "scripts/bootslaves.sh"
          s.args   = ["192.168.33.71", "192.168.33.71", 
		              "192.168.33.61", "192.168.33.62", "192.168.33.63"]
      end
   end
   
   config.vm.define :slave2 do |slave2|
      slave2.vm.box = "ubuntu/trusty64"  
	  slave2.vm.network "private_network", ip: "192.168.33.72"
	  slave2.vm.provider "virtualbox" do |vb|
	     vb.memory = 2048
	     vb.name = "slave2"
      end
      slave2.vm.provision "shell" do |s|
          s.path = "scripts/bootslaves.sh"
          s.args   = ["192.168.33.72", "192.168.33.72", 
		              "192.168.33.61", "192.168.33.62", "192.168.33.63"]
      end
   end
   
   config.vm.define :slave3 do |slave3|
      slave3.vm.box = "ubuntu/trusty64"  
	  slave3.vm.network "private_network", ip: "192.168.33.73"
	  slave3.vm.provider "virtualbox" do |vb|
	     vb.memory = 2048
	     vb.name = "slave3"
      end
      slave3.vm.provision "shell" do |s|
          s.path = "scripts/bootslaves.sh"
          s.args   = ["192.168.33.73", "192.168.33.73", 
		              "192.168.33.61", "192.168.33.62", "192.168.33.63"]
      end
   end
   
end