# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
      config.vm.box = "ubuntu/trusty64"  
	  config.vm.network "private_network", ip: "192.168.33.51"
	  config.vm.provider "virtualbox" do |vb|
	     vb.memory = 2048
	     vb.name = "slave1"
      end
      config.vm.provision :shell, :path => "scripts/bootslave1.sh"
end