# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|  
      config.vm.box = "ubuntu/trusty64"  
	  config.vm.network "private_network", ip: "192.168.33.52"
	  config.vm.provider "virtualbox" do |vb|
	     vb.memory = 4096
	     vb.name = "slave2"
      end
      config.vm.provision :shell, :path => "scripts/bootslave2.sh" 
end